### PR TITLE
Add console as menu item in BM

### PR DESCRIPTION
**Pull request by taurgis**
To give more control on who can see the console in the business manager (e.g. staging) adding this to the bm-extensions file gives you full control of who can use the console in the business manager.

### CODE REVIEW

**Comment by taurgis** [comment]
image

**Comment by taurgis** [comment]
I have read the CLA Document and I hereby sign the CLA.

recheckla

**Comment by taurgis** [comment]
recheckcla

**Comment by taurgis** [comment]
@z1haze @manifestinteractive For some reason I seem to be unable to add the correct label to this pull request.

**Comment by manifestinteractive** [comment]
@taurgis & @z1haze were there more conversation around this that needed to take place?  I saw the two of you had a bit of a conversation in Slack about this, so did not want to start a review on this if there was outstanding work on this.

If there are pending changes, would you mind updating the title with the prefix `[WIP]` to let others know this is a work in progress?  There is also a label for this a well, but if you do not have permission to attach it, I can knock that out.

Pretty excited about this change, so hoping we can get it out in a new release ASAP if there is no more pending work on in.

**Comment by taurgis** [comment]
@manifestinteractive  I am unable to slap labels on pull requests for some reason. But this is (as far as i know) done. Unless you want me to change some things.

Just let me know ;-)

**Review by manifestinteractive — APPROVED** [review]
@z1haze I do not see anything in here that seems to be a deal breaker.  Since you had a previous conversation with @taurgis on this, I will just ask you to give me a sign off on this to make sure it addresses all the known issues you might have discussed externally together.

If it does, let's merge it into our develop branch and I can work on getting any touch up stuff done, and get a new versioned release out with these changes.

**Comment by manifestinteractive** [comment]
@taurgis pending approval from the other author on this one, but wanted to ask if you would desire being added to a new package.json contributors list.  It's a way of adding the names of the people that worked on the project and actually place it in the code.  Feel like you deserve it with all the work you've done ;)

If you would like like, you can hit me up with whatever details you want for https://docs.npmjs.com/cli/v6/configuring-npm/package-json#people-fields-author-contributors ( usually Name, Email & URL ... but we can just do Name's probably if that's cool with you )

**Comment by taurgis** [comment]
hank you @manifestinteractive. Name is fine with me, Github username or real name is ok. (taurgis or Thomas Theunen).

**Comment by manifestinteractive** [comment]
@taurgis will do.  You want me to use the URL to be your GitHub url ?  I did not want to do personal websites or company ones, as that could get ... weird, ha ha ... but GitHub should be safe.

**Comment by taurgis** [comment]
@manifestinteractive Yes, that is fine. I understand.

**Pull request merged**
